### ISSUE TITLE
Dependencies error, Manifest Merger failed after adding the dependency

### ISSUE THREAD

**Issue by shivpujan12** [rtchagas/pingplacepicker#11]
Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [com.github.rtchagas:pingplacepicker:1.0.4] C:\Users\dell\.gradle\caches\transforms-1\files-1.1\pingplacepicker-1.0.4.aar\bea39304e99fc86a33ad7d0ec21ee063\AndroidManifest.xml as the library might be using APIs not available in 16
	Suggestion: use a compatible library with a minSdk of at most 16,
		or increase this project's minSdk version to at least 19,
		or use tools:overrideLibrary="com.rtchagas.pingplacepicker" to force usage (may lead to runtime failures)

**Comment by rtchagas** [comment]
Hi @shivpujan12 

Unfortunately PING minimum SDK is 19 (KitKat) due to some new APIs being used.

If possible you should increase your project's **minSdk to 19** as well.

**Comment by adicatur** [comment]
Hi @rtchagas can I know which APIs that need minimum SDK 19?
