### ISSUE TITLE
The Library Works one time only

### ISSUE THREAD

**Issue by LinkIMSA** [rtchagas/pingplacepicker#12]
The library works one time only 
couldn't load nearby places error keeps showing ,i have tried to add tow key's with restriction on the geolocation and single key without restriction supports all api's Places and Geolocation
with no luck any idea to solve this issue

**Comment by rtchagas** [comment]
@LinkIMSA 

Please follow my comments here https://github.com/rtchagas/pingplacepicker/issues/10
