### ISSUE TITLE
Add support for map pointing

### ISSUE THREAD

**Issue by jmami** [rtchagas/pingplacepicker#20]
Hello rtchagas,

First all thank you for this amazing library. It is exactly what I am looking for.
I would like to add support for map pointing.
My idea is to add a button on top of the gps one, so when is pushed the places requested are those closer to the center of the map (or the ping). This is for a personal app to keep track of my expenses and I usually do this when I am at home, not at supermarket, bar, etc.

I tried to do it myself but I got lost in the function getNearbyPlaces in GoogleMapsRepository, as you do not need to provide a LatLng I guess the system automatically gets the location from the device when building the FindCurrentPlaceRequest.

Again thank you for your time and effort 

Regards,

**Comment by rtchagas** [comment]
This is the same as request as #22 . I'll keep tracking everything in that issue.
