### ISSUE TITLE
The textview color of  location select comfirm dialog  of PlaceConfirmDialogFragment is unvisible.

### ISSUE THREAD

**Issue by DuMintong** [rtchagas/pingplacepicker#28]
![device-2019-07-12-221911](https://user-images.githubusercontent.com/20570319/61134920-3550b280-a4f3-11e9-9718-4a27768a88d1.png)

Hi rtchagas,
    I add the library to my project, and the alertDialog  occur when pick a place. But the positivebutton and nativebutton text is unvisible, and they exist actually.  My project(including application or activity) don't use any theme oy style.  How can this happen?
My device is  one plus phone.

**Comment by rtchagas** [comment]
Hi @DuMintong 

Looks like you have some conflicts with you App Theme and styles.

I would suggest you to switch your app theme to Material Theme. But this can be difficult if your project is already in late development stage.

Instead, try to create a custom Dialog Theme for your app.

```xml
<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
    <!-- ... other AppTheme items ... -->
    <item name="android:alertDialogTheme">@style/CustomAlertDialogTheme</item>
    <item name=alertDialogTheme">@style/CustomAlertDialogTheme</item>
</style>

<style name="CustomAlertDialogTheme" parent="Theme.AppCompat.Light.Dialog.Alert">
    <item name="colorPrimary">@color/colorPrimary</item>
    <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
    <item name="colorAccent">@color/colorAccent</item>
</style>
```
