### ISSUE TITLE
The nearby searches function is unavailable and how to add signature to the request URL 

### ISSUE THREAD

**Issue by DuMintong** [rtchagas/pingplacepicker#29]
Hi  rtchagas,
    Question 1: According to the chapter of "Enabling nearby searches" in your guideline, I add the property to my project, and it's not work. Whether is this featrue unavailable until now.  Next version will work?  When do you release next version that contains the function.
**********************************************************
To do that, enable this flag in your project:
 <bool ### name="enable_nearby_search">true</bool>
*********************************************************

Question 2: How to add a digital signature  to the request URL.
     A requirement as bellow mentioned in google map document("https://developers.google.com/maps/documentation/maps-static/get-api-key#dig-sig-key", chapter "Generating digital signatures"), client can add a digital signature for use with API keys to the request URL. Whether does your SDK support to set this feature. If not, can you 
support it in next release version？ When release next version?
**********************************************************
5、Add the resulting signature to the request URL within a signature parameter. For example:
https://maps.googleapis.com/maps/api/staticmap?center=40.714%2c%20-73.998&zoom=12&size=400x400&key=YOUR_API_KEY&signature=**BASE64_SIGNATURE**
**********************************************************

**Comment by DuMintong** [comment]
Hi rtchagas,
I double check and find nearby search has add on version 1.1.0.   So ignore  question 1.
<bool ### name="enable_nearby_search">

**Comment by rtchagas** [comment]
Hi @DuMintong 

I added the possibility to pass signatures to the requests.

Please check this commit a5caa7f6bc6fd64aa59e803c78e8c400971a38a8

Ping uses 2 APIs  that might need signatures:
- Maps Static API
- Geocoding API

PING calls both APIs above with the [Maps API key](https://github.com/rtchagas/pingplacepicker#api-keys). 
That means that you must encode your signature with the Maps API key passed to PING.

Therefore you must pass two signatures like this:
```java
builder.setAndroidApiKey("YOUR_ANDROID_API_KEY")  
        	.setMapsApiKey("YOUR_MAPS_API_KEY")
                .setSignature(PingPlacePicker.KEY_SIGNATURE_GEOCODING_API, "GEOCODING_SIGNATURE")
                .setSignature(PingPlacePicker.KEY_SIGNATURE_MAPS_STATIC_API, "STATIC_SIGNATURE")
```

I didn't release a new version yet. In order to test this new feature, please change PING dependency to:

```
implementation 'com.github.rtchagas:pingplacepicker:master-SNAPSHOT'
```

Let me now your feedback.

**Comment by DuMintong** [comment]
Hi  rtchagas,
    We have realized this feature thought to modify your source code by project dependency of placepickerlibrary.  I add only one signature to MAP_STATIC_API and other API don't need this.
The signature is generated based on the encoded request URL with a specific algorithm, so I think it can be added before HTTP POST/GET with the request URL.  As for your setSignature() API, I don't know how to add the signature because I don't know the final request URL.  I think the signature can be add in your lib default, and just release an API to enable/disable it.

**Comment by rtchagas** [comment]
Hi @DuMintong 

Please check this new commit. I've added the automatic signing for Maps Static API.
https://github.com/rtchagas/pingplacepicker/commit/5c16d2df710d12c0f903d5a5f691f2d9e84e4c0d

You can use

```java
builder.setUrlSigningSecret("YOUR_SIGNING_SECRET")  
```

Same as before, download it via latest snapshot.
```
implementation 'com.github.rtchagas:pingplacepicker:master-SNAPSHOT'
```

**Comment by rtchagas** [comment]
I'm closing this issue.

If anything is not working as expected, please reopen it.

Thanks
