### ISSUE TITLE
Error: Static interface methods are only supported starting with Android N (--min-api 24)

### ISSUE THREAD

**Issue by OHassini** [rtchagas/pingplacepicker#3]
I can't change my API version to more than 20 this will radically decrease the number of users

**Comment by rtchagas** [comment]
Hi @OussEmaDevCode 

You just need to increase the **compileSdkVersion**.

The **minSdkVersion** don't need to be changed.

Please check the sample project https://github.com/rtchagas/pingplacepicker/blob/master/sample/build.gradle

There the minSdk is 19.

Thanks!
