### ISSUE TITLE
Current location button and dialog buttons are not visible

### ISSUE THREAD

**Issue by chhatrasal09** [rtchagas/pingplacepicker#30]
![photo_2019-07-16 16 13 55](https://user-images.githubusercontent.com/21989289/61288438-befacb80-a7e4-11e9-90d6-972784963d10.jpeg)
![photo_2019-07-16 16 13 59](https://user-images.githubusercontent.com/21989289/61288448-c5894300-a7e4-11e9-9221-9cb8d9c9fe43.jpeg)

**Comment by rtchagas** [comment]
Hi @chhatrasal09 

Thanks for this bug report and solution. Well done.

I merged your PR.
