### ISSUE TITLE
All Constraint Layouts shift to the right

### ISSUE THREAD

**Issue by yalematta** [rtchagas/pingplacepicker#33]
Just when I insert your 
   ` implementation 'com.github.rtchagas:pingplacepicker:1.1.0'`
in my gradle, all the constraintLayouts that I am using in my app shift to the right.
I haven't used its functionality in my app yet, just inserted the implementation and this happened.

What are you using in your library? Which version of constraintLayout?

**Comment by yalematta** [comment]
You are using 
`implementation 'androidx.constraintlayout:constraintlayout:2.0.0-beta2'`
and this is the one causing all the shifts in layouts
If you use 
`implementation 'androidx.constraintlayout:constraintlayout:1.1.3'`
It will work fine. I have tested it. 

Will you release a version with this update soon?

**Comment by yalematta** [comment]
Adding this to my gradle solved it.
```
configurations.all { 
    resolutionStrategy.force 'androidx.constraintlayout:constraintlayout:1.1.3'
}
```

**Comment by rtchagas** [comment]
Hi!

Your constraint layout is too old. 

It's OK to fix the way you did but I strongly suggest you to upgrade to latest one and fix your project. 

The sample project is working fine.
