### ISSUE TITLE
Got a runtime fatal error when clicked search.

### ISSUE THREAD

**Issue by Dararii** [rtchagas/pingplacepicker#42]
![image](https://user-images.githubusercontent.com/7982335/65749938-6a9f9080-e131-11e9-8a91-f8453e2f51e2.png)

Another bug is the map not shown.

![image](https://user-images.githubusercontent.com/7982335/65750002-915dc700-e131-11e9-9129-e272b37dd7de.png)

Seems really wrong with the auth, but I gave set every configuration as the documentation.
This just happen on certain devices, currently only appear in Samsung Galaxy S7 Edge.

Looking forward for your response.
Thanks in advance.

**Comment by rtchagas** [comment]
Hi @Dararii 

That error means that your Android key is wrong.

You must add the SHA1 for your apk (both debug and release) to the Android key configuration.

Probably some apk being tested by you is not signed correctly or its SHA1 was not added to the Android Key.
