### ISSUE TITLE
getRating() and getUserRatingsTotal() always return null

### ISSUE THREAD

**Issue by Moh09** [rtchagas/pingplacepicker#43]
Hello,
No matter the location I choose place.getRating() returns null, even when there are reviews in google maps (getAddress(), getLatLng and getName() work perfectly) .
An idea of why ?
By the way thanks for that place picker !

**Comment by rtchagas** [comment]
Hi @Moh09 

PING doesn't fetch atmosphere data (rating, price, review). This is because they would cost extra US$ 0.005 per request.

PING only fetches these fields.

    /**
     * These fields are not charged by Google.
     * https://developers.google.com/places/android-sdk/usage-and-billing#basic-data
     */
    private fun getPlaceFields(): List<Place.Field> {

        return listOf(
                Place.Field.ID,
                Place.Field.NAME,
                Place.Field.ADDRESS,
                Place.Field.LAT_LNG,
                Place.Field.TYPES,
                Place.Field.PHOTO_METADATAS)
    }

If you really want that data, you can get the place ID returned by PING and fetch via Places API.
