### ISSUE TITLE
cant search location message cant load search result

### ISSUE THREAD

**Issue by mrariffatulloh** [rtchagas/pingplacepicker#44]
![WhatsApp Image 2019-10-07 at 14 08 02](https://user-images.githubusercontent.com/55747759/66305014-a6eca100-e928-11e9-9a13-52bdef4ea70e.jpeg)

can you help me for this problem

**Comment by rtchagas** [comment]
Hi @mrariffatulloh 

You Android Key is probably wrong.
Please check https://github.com/rtchagas/pingplacepicker#api-keys to learn how to add the right keys.

BR,
