### ISSUE TITLE
Does it requiere only Places API service?

### ISSUE THREAD

**Issue by slabiak** [rtchagas/pingplacepicker#5]
Hi! Does your library require "Places SDK for Android" to be enabled (like original googles place picker)? Or maybe it is enough to have just new "Places API" enabled to have it working? Please see this thread https://stackoverflow.com/questions/55520975/place-picker-google-maps-closes-immediately-although-i-have-followed-the-steps/55524719#55524719

**Comment by rtchagas** [comment]
Hi @slabiak 

Yes, this library requires "Places SDK for Android".

This is the new entry point for Places and we need to switch to it.
