### ISSUE TITLE
Cannot get place name

### ISSUE THREAD

**Issue by EdozdeDandez** [rtchagas/pingplacepicker#52]
I'm using this package for loading a place picker but I can't seem to get the name of the selected place. The getName function returns the coordinates of the place in degrees and direction format  i.e 1° 17' 52" S, 36° 45' 54. How can I get the name of the place?

**Comment by rtchagas** [comment]
Hi @EdozdeDandez 

This issue happens because your Maps API key is wrong and PING can't load the place details through Geocode API.

Please be sure that GeoCode API is enabled in your key and you correctly added the key to you project.
