### ISSUE TITLE
Forcing user to enable location detection

### ISSUE THREAD

**Issue by mrgames13** [rtchagas/pingplacepicker#53]
Hi,
I have a simple question regarding the search bar. Why is the user only able to search when he enables location detection on his device? Wouldn't it be better to allow searching also when the user has location detection disabled?
Thanks in advance.

**Comment by rtchagas** [comment]
Hi @mrgames13 

This is not a PING requirement but Google Places library's actually.

It simply crashes when we perform a search without location enabled.

BR,
