### ISSUE TITLE
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.sample/com.rtchagas.pingplacepicker.ui.PlacePickerActivity}: android.view.InflateException: Binary XML file line #43: Binary XML file line #43: Error inflating class fragment

### ISSUE THREAD

**Issue by shubh8101996** [rtchagas/pingplacepicker#57]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.sample/com.rtchagas.pingplacepicker.ui.PlacePickerActivity}: android.view.InflateException: Binary XML file line #43: Binary XML file line #43: Error inflating class fragment

**Comment by rtchagas** [comment]
Hi @shubh8101996 
This line is where PING inflates the Google Maps fragment.
Please make sure you have added the maps api to your project.
In case of doubt, please check the sample. It is working as expected.
