### ISSUE TITLE
Select this location still error

### ISSUE THREAD

**Issue by paloe** [rtchagas/pingplacepicker#60]
Hi, fix this bug please

**Comment by rtchagas** [comment]
Hi @paloe 
What kind of error are you facing? Please provide the stack trace.

**Comment by rtchagas** [comment]
Please reopen this if you still face problems with the latest version.

**Comment by paloe** [comment]
halo, sorry for so long reply,
error : if i click "Select this location" can't get lat and long so thumbail/image map can't showing.

sorry for my bad english
