### ISSUE TITLE
Select this location does not return the actual LatLng

### ISSUE THREAD

**Issue by mahasadhu** [rtchagas/pingplacepicker#62]
Hi Rafael, thank you for this awesome library.

When users click on select this location button, the library does not return the actual LatLng selected by the users. Instead it only return place object retrieved from the Google Place.

It becomes a problem when the app needs the actual coordinate selected by the users. I will submit a PR

**Comment by rtchagas** [comment]
I've release the version 2.0.3 with the fix :)
