### ISSUE TITLE
Android resource compilation failed

### ISSUE THREAD

**Issue by febinmathew** [rtchagas/pingplacepicker#7]
C:\<ProjectName>\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:6077: error: duplicate value for resource 'attr/progress' with config ''.
C:\<ProjectName>\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:6077: error: resource previously defined here.
C:\<ProjectName>\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:6267: error: duplicate value for resource 'attr/rotation' with config ''.
C:\<ProjectName>\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:6267: error: resource previously defined here.

**Comment by rtchagas** [comment]
@febinmathew 

PING doesn't have any resource with those names (progress and rotation).
However, its dependencies may have.

So, I can't change those dependencies and you might try to check if your project's resources can be renamed.

Hope it helps.
