### ISSUE TITLE
Search result unavailable

### ISSUE THREAD

**Issue by ghiyatshanif** [rtchagas/pingplacepicker#73]
First of all, This is an awesome replacement of the original PlacePicker library, however I found some trouble using your library. most of the times the search location feature are not showing any result when i insert a long query. but sometimes it show some result when i only insert one or two letters on the search bar. this is what I meant:

Cant load search result:
![Cant load search result:](https://user-images.githubusercontent.com/44795331/82013944-ba719e80-96a5-11ea-8339-4cd6fef67673.png)

![Search result loaded](https://user-images.githubusercontent.com/44795331/82013992-d37a4f80-96a5-11ea-80d7-9112c514ceb2.png)

also, I am unable to search for specific location with the search bar. 

this is how I implement your library:
```
private fun showPlacePicker() {
        val builder = PingPlacePicker.IntentBuilder()
        builder.setAndroidApiKey(getString(string.android_api_key))
            .setMapsApiKey(getString(string.maps_api_key))

        try {
            val placeIntent = builder.build(this)
            startActivityForResult(placeIntent, REQUEST_PLACE_PICKER)
        } catch (ex: Exception) {
            showToast("Google Play Services is not Available")
        }
    }
```
on the manifest :

``` 
<meta-data
            android:name="com.google.android.geo.API_KEY"
            android:value="@string/android_api_key" />
```

and this is my API key configuration : 
**Map Api Key :**
![image](https://user-images.githubusercontent.com/44795331/82014180-4b487a00-96a6-11ea-9c89-bef8dd4160af.png)

**Android Api key :**
![image](https://user-images.githubusercontent.com/44795331/82014243-661aee80-96a6-11ea-8b5f-ab4c73912d21.png)

Am I missing something here? thanks in advance @rtchagas !

**Comment by rtchagas** [comment]
Hello @ghiyatshanif 

The only thing that I could notice is that you're restricting your Android API more than you should.

You should restrict it only by Android applications and set the SHA1s that you might need.

You should not restrict it by APIs.

**Comment by ghiyatshanif** [comment]
i've already adjusted the credentials settings as per your suggestion but it doesn't affect anything, **this is a dumb question** but, do we need to set up the billing first? I dont really understand their pricing mechanism these days. @rtchagas

**Comment by rtchagas** [comment]
Hello!

Yes, according to Google, you do need to setup billing first.

The model is pay as you go. You can check the prices at the README of the
library.

Stay safe,
