### ISSUE TITLE
ERROR: Failed to resolve: com.github.rtchagas:pingplacepicker:1.0.3

### ISSUE THREAD

**Issue by Rahul-Openxcell** [rtchagas/pingplacepicker#8]
@rtchagas 
Thanks for update...
I have add this dependencies in build.gradle file :

```
implementation 'com.google.android.libraries.places:places:1.1.0'
implementation 'com.github.rtchagas:pingplacepicker:1.0.3'
```

and also add 
```
allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}
```

**Comment by rtchagas** [comment]
Hi @Rahul-Openxcell 

Yes, I already mentioned that in the README.
https://github.com/rtchagas/pingplacepicker#download

Thanks for all your feedback.

**Comment by Rahul-Openxcell** [comment]
Hi @rtchagas 
I have add your mentioned that in the README.
but again error for download dependencies
` ERROR: Failed to resolve: com.github.rtchagas:pingplacepicker:1.0.3 `

**Comment by rtchagas** [comment]
Please, just try to sync again.

I forced a refresh in Jitpack.
https://jitpack.io/#rtchagas/pingplacepicker/1.0.3
