### ISSUE TITLE
Select Location text not visible

### ISSUE THREAD

**Issue by jaseelmohd** [rtchagas/pingplacepicker#82]
Thanks for the great library!,

Please check the below screenshot, the Select location text is not visible on both dark and light theme
![Screenshot_20201015-205806](https://user-images.githubusercontent.com/23740454/96151835-7e2ebc80-0f29-11eb-8ab0-2edb883f005a.jpg)

**Comment by tangent-q** [comment]
@rtchagas facing same issue.

It doesn't seem like a theme or colouring conflict issue. Upon doing the layout inspection, seems like TextView (android:id="@+id/tvLocationSelect") has gone to the top of it's parent and has no width/height.

https://github.com/rtchagas/pingplacepicker/blob/master/library/src/main/res/layout/activity_place_picker.xml#L96

What do you think ?

**Comment by tangent-q** [comment]
@rtchagas 
Sorry, was using an older version. Updated to the latest 2.2.0 and issue resolved. But it's strange that Gradle wasn't highlighting me that there is an update available. May be while releasing some attributes needs to be set.

@jazeelmohd are you on the latest version ? may be updating will solve your issue.

**Comment by jaseelmohd** [comment]
> @rtchagas
> Sorry, was using an older version. Updated to the latest 2.2.0 and issue resolved. But it's strange that Gradle wasn't highlighting me that there is an update available. May be while releasing some attributes needs to be set.
> 
> @jazeelmohd are you on the latest version ? may be updating will solve your issue.

Just updated now, and it is visible properly
