### ISSUE TITLE
No location pick using marker on Map

### ISSUE THREAD

**Issue by Rahul-Openxcell** [rtchagas/pingplacepicker#9]
Hi @rtchagas 

When i am pick location  using centre marker.
show toast "Could't find the selected place"

**Comment by rtchagas** [comment]
I've tested the demo project and it is working fine.

Please check if you have a valid geolocation API key.

**Comment by vanyasem** [comment]
I'm having the same issue. My geolocation API key is valid

**Comment by rtchagas** [comment]
Please check my answer here:
https://github.com/rtchagas/pingplacepicker/issues/10#issuecomment-490636289
