### ISSUE TITLE
Error Android 11 (sdk 30)

### ISSUE THREAD

**Issue by fabiodsnmatos** [rtchagas/pingplacepicker#91]
When I try to update my app to android 30, the pingplacepicker gives an error opening on devices with android 11. 
Will there be any update to make the component compatible with the target 30?
urgente, please. @rtchagas

**Comment by rtchagas** [comment]
Hello @fabiodsnmatos 
The current PING version already targets SDK 30 and was tested on many Android 11 devices. Actually my current device is running Android 11.

Please describe better the issue you are facing. Also, please add the stack trace of the error.
